#:import hexColor kivy.utils.get_color_from_hex
#:import FadeTransition kivy.uix.screenmanager.FadeTransition
#:import TextInput kivy.uix.textinput
#:import DropDown kivy.uix.dropdown

#########################################################################################################################
#                                       STARTUP WINDOW
#########################################################################################################################
<StartUpWindow>:
    BoxLayout:
        # box orientation
        orientation: 'vertical'
        # set canvas for background image
        canvas.before:
            Rectangle:
                pos: self.pos
                size: root.width, root.height
                source:'C:\zf visual resources\ZF_Level2_coASSIST_System_Blue.jpg'
        Button:
            text: "Click to start!"
            pos_hint :{'center_x':0.5, 'center_y':0.5}
            size_hint: 100, 0
            # set opacity ratio
            background_color: (0.0, 0.0, 0.0, 0.0)
            font_size: 40
            on_release:
                root.manager.transition = FadeTransition()
                root.manager.transition.direction = 'up'
                root.manager.current = 'main_window'
#########################################################################################################################
#                                       MAIN WINDOW
#########################################################################################################################
<MainWindow>:
    GridLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: root.width, root.height
                source:'C:\zf visual resources\ZF_Desktophintergrund-1920x1080.jpg'
        rows:3

        BoxLayout:
            # box orientation
            orientation:'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.19),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            #Image:
            #    source: 'C:\zf visual resources\01_zf_logo2.png'
            #    pos_hint:{"right":1,"top":1}
            #    allow_stretch: True
            #    size_hint_x: None
            #    size_hint_y: None
            #    # scale with window
            #    width: root.width/5
            #    height: root.height/5
            #    keep_ratio: True

        BoxLayout:
            # box orientation
            orientation:'vertical'
            # distance between childrens in box layout
            spacing: 10
            Button:
                id: scenario_btn
                text: 'Scenario Runner'
                size_hint: .4, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'up'
                    root.manager.current = 'scenario_runner_window'

            Button:
                id: manual_mode_btn
                text: 'Manual Mode'
                size_hint: .4, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'up'
                    root.manager.current = 'manual_window'
        BoxLayout:
            orientation: 'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.5),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            Button:
                id: exit_btn
                text: 'Exit'
                size_hint: .3, 0
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'up'
                    root.manager.current = 'startup_window'
#########################################################################################################################
#                                       SCENARIO RUNNER
#########################################################################################################################
<ScenarioRunnerWindow>:
    GridLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: root.width, root.height
                source:'C:\zf visual resources\ZF_Desktophintergrund-1920x1080.jpg'
        rows:4

        BoxLayout:
            # box orientation
            orientation:'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.19),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            #Image:
            #    source: 'C:\zf visual resources\01_zf_logo2.png'
            #    pos_hint:{"right":1,"top":1}
            #    allow_stretch: True
            #    size_hint_x: None
            #    size_hint_y: None
            #    # scale with window
            #    width: root.width/5
            #    height: root.height/5
            #    keep_ratio: True

        BoxLayout:
            # box orientation
            orientation:'horizontal'
            # distance between childrens in box layout
            spacing: 10
            ToggleButton:
                id: tutorial_btn
                text: 'Tutorial scenarios'
                size_hint: .5, 0
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                # set default state on start
                state: 'down'
                # assign to group to allow only one to be 'down'
                group: 'mode_selection'
                # behavior when toggled 'down'
                on_state:

            ToggleButton:
                id: challenge_btn
                text: 'Challenge scenarios'
                size_hint: .5, 0
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                # assign to group to allow only one to be 'down'
                group: 'mode_selection'
                # behavior when toggled 'down'
                on_state:

        BoxLayout:
            orientation:'vertical'
            spacing: 5
            Label:
                id: dropdown_label
                text:'Dropdown widget'
                font_size: 15
            BoxLayout:
                Spinner:
                    id: spinner_id
                    # top listed thing
                    text: 'List of scenarios...'
                    size_hint: None, None
                    size:300,100
                    values: ['item 1', 'item 2', 'item 3']
                    # set color to zf_blue
                    background_color: hexColor('#1179BF')
                    on_text: root.spinner_clicked(spinner_id.text)
                Button:
                    text: "Run"
                    size_hint: .1, 0.5
                    on_press:
                        root.manager.transition = FadeTransition()
                        root.manager.transition.direction = 'up'
                        root.manager.current = 'tutorial_window'
                        #app.player()


        BoxLayout:
            orientation: 'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.5),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            Button:
                id: scenario_runner_back_btn
                text: 'Back'
                size_hint: .3, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'main_window'
#########################################################################################################################
#                                       TUTORIAL SCENARIOS
#########################################################################################################################
<TutorialScenariosWindow>:
    AnchorLayout:
        # position of anchor layout
        anchor_x: 'center'
        anchor_y: 'center'
        BoxLayout:
            orientation: 'vertical'
            # distance between box layout and children [left,top,right,bottom]
            padding: [10,0,0,150]
            # distance between childrens in box layout
            spacing: 5
            # set background image
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: root.width, root.height
                    source:'C:\zf visual resources\ZF_Desktophintergrund-1920x1080.jpg'

            #Image:
            #    source: 'C:\zf visual resources\01_zf_logo2.png'
            #    pos_hint:{"right":1,"top":1}
            #    allow_stretch: True
            #    size_hint_x: None
            #    size_hint_y: None
            #    # scale with window
            #    width: root.width/5
            #    height: root.height/5
            #    keep_ratio: True
        BoxLayout:
            orientation: 'horizontal'
            padding: 10
            spacing: 5
            Label:
                text: 'to do'
                background_color: hexColor('#1179BF')
            BoxLayout:
                id:bl
                orientation: 'vertical'
                # distance between box layout and children [left,top,right,bottom]
                padding: 10, 10
                row_default_height: '48dp'
                row_force_default: True
                # distance between childrens in box layout
                spacing: 10
                ScrollView:
                    size: self.size
                    GridLayout:
                        id: layout_content
                        size_hint_y: None
                        cols: 1
                        row_default_height: '20dp'
                        row_force_default: True
                        spacing: 0, 0
                        padding: 0, 0
                        BoxLayout:
                            orientation: 'horizontal'
                            spacing: 5
                            Label:
                                text: 'Current voltage'
                            Label:
                                id: current_voltage
                                text: 'XX.X V'
                        Label:
                            text: 'obj 3'
                        Label:
                            text: 'obj 4'
                        Label:
                            text: 'obj 5'
                        Label:
                            text: 'obj 6'
                        Label:
                            text: 'obj 7'
                        Label:
                            text: 'obj 8'
                        Label:
                            text: 'obj 9'
            BoxLayout:
                id:bl2
                orientation: 'vertical'
                # distance between box layout and children [left,top,right,bottom]
                padding: 10, 10
                row_default_height: '48dp'
                row_force_default: True
                # distance between childrens in box layout
                spacing: 10
                ScrollView:
                    do_scroll: False, True # x_axis scroll, y_axis scroll
                    bar_width: dp(10)
                    scroll_type: ['bars','content'] # bar follows content scroll
                    size: self.size
                    GridLayout:
                        id: layout_content
                        size_hint_y: None
                        cols: 1
                        row_default_height: '20dp'
                        row_force_default: True
                        spacing: 0, 0
                        padding: 0, 0
                        BoxLayout:
                            orientation: 'horizontal'
                            canvas.before:
                                Color:
                                    rgba: 1,1,1,1
                                Rectangle:
                                    pos: self.pos
                                    size: self.size
                            Button:
                                id: set_user_voltage
                                text: 'SET'
                                on_press:
                                    app.GetUserVoltage(textInput.text)
                            TextInput:
                                id: textInput
                                hint_text: 'Insert voltage'
                                pos_hint:{'center_x':0.5,'center_y':0.7}
                                size_hint: (1.2, 1.3)
                                cursor_blink: True
                                use_bubble: True
                                multiline: False
                                disabled_foreground_color: hexColor("#363940")
                                input_filter: 'float'
                        BoxLayout:
                            orientation: 'horizontal'
                            spacing: 5
                            Button:
                                id: left_blinker
                                text: 'LEFT'
                                on_release:
                                    #app.XXXX()
                            Button:
                                id: right_blinker
                                text: 'RIGHT'
                                on_release:
                                    #app.XXXX()
                        Button:
                            text: 'video'
                            on_press:
                                app.player()
                        Label:
                            text: 'obj 4'
                        Label:
                            text: 'obj 5'
                        Label:
                            text: 'obj 6'
                        Label:
                            text: 'obj 7'
                        Label:
                            text: 'obj 8'
        BoxLayout:
            orientation: 'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.5),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            Button:
                id: tutorial_back_btn
                text: 'Back'
                size_hint: .4, 0
                pos_hint :{'center_x':1, 'center_y':0.08}
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'scenario_runner_window'
#########################################################################################################################
#                                       CHALLENGE SCENARIOS
#########################################################################################################################
<ChallengeScenariosWindow>:
    AnchorLayout:
        # position of anchor layout
        anchor_x: 'center'
        anchor_y: 'center'

        BoxLayout:
            orientation: 'vertical'
            # distance between box layout and children [left,top,right,bottom]
            padding: [10,0,0,150]
            # distance between childrens in box layout
            spacing: 5
            # set background image
            canvas.before:
                Rectangle:
                    pos: self.pos
                    size: root.width, root.height
                    source:'C:\zf visual resources\ZF_Desktophintergrund-1920x1080.jpg'
            #Image:
                #source: 'C:\zf visual resources\01_zf_logo2.png'
                #pos_hint:{"right":1,"top":1}
                #allow_stretch: True
                #size_hint_x: None
                #size_hint_y: None
                ## scale with window
                #width: root.width/5
                #height: root.height/5
                #keep_ratio: True

            Button:
                id: challenge_back_btn
                text: 'Back'
                size_hint: .4, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'scenario_runner_window'
#########################################################################################################################
#                                       MANUAL SCENARIOS
#########################################################################################################################
<ManualModeWindow>:
    GridLayout:
        canvas.before:
            Rectangle:
                pos: self.pos
                size: root.width, root.height
                source:'C:\zf visual resources\ZF_Desktophintergrund-1920x1080.jpg'
        rows:3

        BoxLayout:
            # box orientation
            orientation:'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.19),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            #Image:
                #source: 'C:\zf visual resources\01_zf_logo2.png'
                #pos_hint:{"right":1,"top":1}
                #allow_stretch: True
                #size_hint_x: None
                #size_hint_y: None
                ## scale with window
                #width: root.width/5
                #height: root.height/5
                #keep_ratio: True

        BoxLayout:
            # box orientation
            orientation:'vertical'
            # distance between childrens in box layout
            spacing: 10
            Button:
                text: 'Some widgets'
                size_hint: .4, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
            Button:
                text: 'Some widgets too'
                size_hint: .4, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                # set opacity ratio
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20

        BoxLayout:
            orientation: 'horizontal'
            # distance between box layout and children [left,top,right,bottom]
            padding: [(root.width/1.5),0,0,0]
            # distance between childrens in box layout
            spacing: 5
            Button:
                id: manual_back_btn
                text: 'Back'
                size_hint: .3, 0
                pos_hint :{'center_x':0.5, 'center_y':0.5}
                background_color: (0.8, 0.8, 0.8, 0.8)
                font_size: 20
                on_press:
                    root.manager.transition = FadeTransition()
                    root.manager.transition.direction = 'down'
                    root.manager.current = 'main_window'