<MyGrid>
    GridLayout:
        cols: 1
        size: root.width, root.height

        GridLayout:
            cols: 2

            Label:
                text: "text1"

            TextInput:
                multiline: False

            Label:
                text: "text2"

            TextInput:
                multiline: False

            Button:
                text: "Click"
                background_color: [1,0,0,1]
                font_size: 32